### PR TITLE
Header.marshal, checksum: check length

### LINKED ISSUE #144: Tar.Header.marshal computes incorrect checksum when buffer is larger than Tar.Header.length and is non-zero
Now I am struggling to write a reproducing example, but I had `Tar.Header.marshal buf hdr` which produced a new checksum every time even if the file was the same. Then I rewrote it to `Tar.Hheader.marshal (Cstruct.sub buf 0 Tar.Header.length) hdr` and the checksum was correct. It was a very long buffer with some random data near the end. It seems the header checksum is computed over the *whole* buffer, but we should only consider the first 512 bytes (the actual header).

This was observed in tar.2.6.0, but it seems it's an issue with main branch judging from the source code.

### PR DESCRIPTION
**Pull request by reynir**
Fixes #144.

### CODE REVIEW

File: lib/tar.ml [hunk 1]
```diff
@@ -577,6 +578,11 @@ module Header = struct
   (** Marshal a header block, computing and inserting the checksum *)
   let marshal ?level c (x: t) =
     let level = compatibility level in
+    let* () =
+      if Bytes.length c < length then
+        Error (`Msg "buffer too short")
+      else Ok ()
+    in
```
Comment (reynir) [inline lib/tar.ml:585]: Here I'm more inclined to raise `Invalid_argument _`. I decided to allow for longer buffers in case the caller wants to put the file contents in the same buffer. Now, maybe `marshal` could take an `?off` argument...
